gold:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: gold
    username: root
    password: 11Hope17!

  redis:
    host: localhost
    port: 6379
    password: hope1117
    database: 1
