server:
  port: 8081

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${gold.datasource.driver-class-name}
      url: jdbc:mysql://${gold.datasource.host}:${gold.datasource.port}/${gold.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${gold.datasource.username}
      password: ${gold.datasource.password}
  redis:
    host: ${gold.redis.host}
    port: ${gold.redis.port}
    password: ${gold.redis.password}
    database: ${gold.redis.database}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: gold.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    gold:
      mapper: debug
      service: info
      controller: info

gold:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    user-secret-key: increase
    # 设置jwt过期时间
    user-ttl: 7200000
    # 设置前端传递过来的令牌名称
    user-token-name: Authorization