server:
  port: 8081

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${gold.datasource.driver-class-name}
      url: jdbc:mysql://${gold.datasource.host}:${gold.datasource.port}/${gold.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${gold.datasource.username}
      password: ${gold.datasource.password}
  redis:
    host: ${gold.redis.host}
    port: ${gold.redis.port}
    password: ${gold.redis.password}
    database: ${gold.redis.database}
  rabbitmq:
    host: ${gold.rabbitmq.host}
    port: ${gold.rabbitmq.port}
    virtual-host: ${gold.rabbitmq.virtual-host}
    username: ${gold.rabbitmq.username}
    password: ${gold.rabbitmq.password}
    publisher-confirm-type: ${gold.rabbitmq.publisher-confirm-type}
    publisher-returns: ${gold.rabbitmq.publisher-returns}
    connection-timeout: ${gold.rabbitmq.connection-timeout}  # MQ连接超时时间
    template:
      retry:
        enabled: ${gold.rabbitmq.template.retry.enabled}            # 开启超时重试
        initial-interval: ${gold.rabbitmq.template.retry.initial-interval}  # 失败后初始等待时间
        multiplier: ${gold.rabbitmq.template.retry.multiplier}      # 再次失败后等待倍数
        max-attempts: ${gold.rabbitmq.template.retry.max-attempts}  # 最大重试倍数



mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: gold.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true



logging:
  level:
    gold:
      mapper: debug
      service: info
      controller: info

gold:
  jwt:
    user-secret-key: ${gold.jwt.user-secret-key}
    user-ttl: ${gold.jwt.user-ttl}
    user-token-name: ${gold.jwt.user-token-name}

  resend:
    from: ${gold.resend.from}
    ak: ${gold.resend.ak}
