server:
  port: 8080

spring:
  profiles:
    active: release
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${gold.datasource.driver-class-name}
      url: jdbc:mysql://${gold.datasource.host}:${gold.datasource.port}/${gold.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${gold.datasource.username}
      password: ${gold.datasource.password}
  redis:
    host: ${gold.redis.host}
    port: ${gold.redis.port}
    password: ${gold.redis.password}
    database: ${gold.redis.database}
  rabbitmq:
    host: ${gold.rabbitmq.host}
    port: ${gold.rabbitmq.port}
    virtual-host: ${gold.rabbitmq.virtual-host}
    username: ${gold.rabbitmq.username}
    password: ${gold.rabbitmq.password}
    publisher-confirm-type: ${gold.rabbitmq.publisher-confirm-type}
    publisher-returns: ${gold.rabbitmq.publisher-returns}
    connection-timeout: ${gold.rabbitmq.connection-timeout}  # MQ连接超时时间
    template:
      retry:
        enabled: ${gold.rabbitmq.template.retry.enabled}            # 开启超时重试
        initial-interval: ${gold.rabbitmq.template.retry.initial-interval}  # 失败后初始等待时间
        multiplier: ${gold.rabbitmq.template.retry.multiplier}      # 再次失败后等待倍数
        max-attempts: ${gold.rabbitmq.template.retry.max-attempts}  # 最大重试倍数

  kafka:
    bootstrap-servers: ${gold.kafka.bootstrap-servers}  # Kafka 的地址（通常为 broker 地址，多个地址用逗号分隔）
    consumer:
      auto-offset-reset: ${gold.kafka.consumer.auto-offset-reset}           # 如果没有偏移量信息，则从最早的消息开始消费
      enable-auto-commit: ${gold.kafka.consumer.enable-auto-commit}              # 自动提交偏移量
      auto-commit-interval: ${gold.kafka.consumer.auto-commit-interval}          # 自动提交偏移量的时间间隔
      key-deserializer: ${gold.kafka.consumer.key-deserializer}   # Key 的序列化器
      value-deserializer: ${gold.kafka.consumer.value-deserializer} # Value 的序列化器
      spring.json.trusted.packages: ${gold.kafka.consumer.spring.json.trusted.packages}  # 允许反序列化所有包下的类型
    producer:
      retries: ${gold.kafka.producer.retries}                            # 生产者的最大重试次数
      acks: ${gold.kafka.producer.acks}                             # 确认级别（all 表示 leader 和所有副本都确认才算成功）
      key-serializer: ${gold.kafka.producer.key-serializer}   # Key 的序列化器
      value-serializer: ${gold.kafka.producer.value-serializer} # Value 的序列化器
    listener:
      concurrency: ${gold.kafka.listener.concurrency}                        # 并发消费线程数

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: gold.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true


logging:
  level:
    gold:
      mapper: debug
      service: info
      controller: info

gold:
  jwt:
    user-secret-key: ${gold.jwt.user-secret-key}
    user-ttl: ${gold.jwt.user-ttl}
    user-token-name: ${gold.jwt.user-token-name}

  resend:
    from: ${gold.resend.from}
    ak: ${gold.resend.ak}

  domain:
    url: ${gold.domain.url}

  python-http:
    url: ${gold.python-http.url}